CREATE TABLE Cliente (
  idCliente INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(200) NULL,
  PRIMARY KEY(idCliente)
);

CREATE TABLE Filmes (
  idFilmes INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(200) NULL,
  prvenda NUMERIC NULL,
  estoque INTEGER UNSIGNED NULL,
  PRIMARY KEY(idFilmes)
);

CREATE TABLE Vendas (
  idVendas INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idCliente INTEGER UNSIGNED NOT NULL,
  dataVenda DATETIME NULL,
  total NUMERIC NULL,
  idFilme int(10) NOT NULL,
  PRIMARY KEY(idVendas),
  INDEX Vendas_FKIndex1(idCliente)
);


